POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Testovich",
    "email": "test2@test.test",
    "password": "Test1@23",
    "isMale": true,
    "birthday": "1988-04-04"
}